### ISSUE TITLE
Support trailing whitespace

### ISSUE THREAD

**Issue by xixixao** [jonschlinkert/sublime-monokai-extended#26]
For example, I use

``` xml
    <dict>
      <key>name</key>
      <string>TrailingWhitespace</string>
      <key>scope</key>
      <string>trailingwhitespace</string>
      <key>settings</key>
      <dict>
                <key>foreground</key>
                <string>#222222</string>    
      </dict>
    </dict>
```

It would be nice if this was included by default, so that updates don't break it / or I don't have to update manually. Of course, name can be changed.

**Comment by jonschlinkert** [comment]
closing based on age, but I'd still be happy to review a pr for this, especially if it's a configuration option for the user.
