### ISSUE TITLE
Here's a grunt thingy....

### ISSUE THREAD

**Issue by PAEz** [jonschlinkert/sublime-monokai-extended#35]
As an exercise to play with grunt and yaml and handlebars, I made this...
https://dl.dropboxusercontent.com/u/3610419/SublimeThemes/SublimeThemes.zip

Its this theme redone as yaml in a simpler syntax and its all put together with handlebars.
If you run grunt it will compile this theme in the Themes directory.
In the Themes directory is a Monokai directory, thats where the yml is stored.
The colour yml files should be pretty obvious, the only file that'd need explaining I guess is the colours.yml file.
It lists the files of colours to add to the theme and in what order, the files are in the colours directory.
The presets bit lets you name colours that you can then reference in your yaml.  Just put the handle bars notation in quotes or yaml thinks its an object.  I havent made use of this yet, but I plan on grouping like colours with it, theres 14 colours in that theme that are used three or more times.
Anyway, I like the way it turned out, hope you like it.

**Comment by jonschlinkert** [comment]
closing based on age. hope you're all still creating awesome stuff!
