### ISSUE TITLE
Doesn't highlight fenced JavaScript

### ISSUE THREAD

**Issue by chrisranderson** [jonschlinkert/sublime-monokai-extended#41]
This text is all white for me:

```
```javascript
	var http = require('http');
	http.createServer(function (req, res) {
	  res.writeHead(200, {'Content-Type': 'text/plain'});
	  res.end('Hello World\n');
	}).listen(1337, '127.0.0.1');
	console.log('Server running at http://127.0.0.1:1337/');
```
(There are backticks closing the block)

Great work, btw! Loving the markdown.

**Comment by jonschlinkert** [comment]
have you tried removing the leading indentation? code should either be indented or wrapped in code fences, but I don't believe the commonmark spec defines anything that says it should do both. 

<pre>
```js
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```
</pre>

**Comment by chrisranderson** [comment]
Nope, tried this with js and javascript:

```javascript
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```

Here is the file: https://github.com/byu-osl/city-issue-server/blob/master/README.md

**Comment by jonschlinkert** [comment]
> How did you get it to format correctly?

I always use `<pre></pre>` to wrap code when backticks are part of the example. there are other ways to make it work, but not reliably in my experience...

Here is what it looks like for me:

![screen shot 2015-03-12 at 3 00 52 pm](https://cloud.githubusercontent.com/assets/383994/6625784/a22178c4-c8c8-11e4-811c-9efe22999ee0.png)

**Comment by jonschlinkert** [comment]
Also, make sure you go to `view > syntax > Open all with current extension as...` and choose `Markdown Extended`.

**Comment by chrisranderson** [comment]
There we go. I'm not even sure exactly why it was fixed, tbh. I'm using a markdown editing plugin that has some weird style things - I had to change the settings for that plugin to use monokai extended. Thanks for your help.

**Comment by jonschlinkert** [comment]
:+1: no worries
