### ISSUE TITLE
Prettier Support for JSON with MonokaiJsonPlus

### ISSUE THREAD

**Issue by bucaran** [jonschlinkert/sublime-monokai-extended#44]
Any chance we could see this happen during my lifetime?

[MonokaiJsonPlus styles for JSON are rad](https://github.com/ColibriApps/MonokaiJsonPlus) and make a slick sidekick to Sublime Monokai Extended. 

How can I get started with this?

**Comment by jonschlinkert** [comment]
I personally prefer the styling how it is, if there is a way to support both, that would be my preferred route.

**Comment by bucaran** [comment]
I see. I think you are right. MonokaiJsonPlus is perhaps too unconventional for MonokaiExtended. I have, however, no idea how I would replace only the JSON styles in my MonokaiExtended copy.

**Comment by jonschlinkert** [comment]
Hmm, really not sure. wish I knew enough to help. closing for now, but let me know if you find anything out.

**Comment by bucaran** [comment]
Sure. Thanks!
