### ISSUE TITLE
windows XP: monokai-extended doesn't work 

### ISSUE THREAD

**Issue by yijunlw** [jonschlinkert/sublime-monokai-extended#46]
i followed the instruction to install the monokai-extended, but when i write a markdown file, the highlight doesn't work , what's the problem? thank you ?

winxp sublime text 3 3083

**Comment by jonschlinkert** [comment]
do you have a markdown syntax highlighting package installed? maybe try using https://github.com/jonschlinkert/sublime-markdown-extended

**Comment by jonschlinkert** [comment]
closing due to lack of response and age
