### ISSUE TITLE
url is not highlighted in sublime text 3

### ISSUE THREAD

**Issue by Lin07ux** [jonschlinkert/sublime-monokai-extended#60]
a url href in a plain text will be highlight in sb2, but no highlight in sb3.
![qq 20160104104235](https://cloud.githubusercontent.com/assets/8132527/12082594/f26fb2b8-b2cf-11e5-8df9-bf2c900e0a5f.png)

**Comment by jonschlinkert** [comment]
sorry for the late reply, closing since I don't think this is related to this package. it appears to be an ST issue.
