### ISSUE TITLE
TODO: colors that broke in ST build 3013

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/sublime-monokai-extended#63]
PRs would be great for any of the following (scopes seem to have changed, so I'll have to look these up when I get a chance):

- [ ] In the following `.toUpperCase()` should be `#66d9ef`

<img width="214" alt="screen shot 2016-02-10 at 10 59 37 pm" src="https://cloud.githubusercontent.com/assets/383994/12969135/02c705a2-d04a-11e5-9e7b-7b7680502766.png">

- [ ] in the following, the `-` in `-1` should be `f92672`

<img width="192" alt="screen shot 2016-02-10 at 11 01 27 pm" src="https://cloud.githubusercontent.com/assets/383994/12969150/4846e822-d04a-11e5-94c7-7cd316380070.png">

**Comment by SuperPaintman** [comment]
[ ] in function arguments, the `,` should be `#F8F8F2`
![monokai_extend_js](https://cloud.githubusercontent.com/assets/8445785/12975271/289862d4-d0dc-11e5-9ced-1b05b0cc5c11.PNG)
