### ISSUE TITLE
Syntax Requires Change

### ISSUE THREAD

**Issue by seshaljain** [jonschlinkert/sublime-monokai-extended#65]
I installed this package to work with my Jekyll projects, and was quite impressed. However, for any syntax other than Markdown, it seems I have to change it first to Markdown Extended. Is there any workaround for this?

**Before**
![before](https://cloud.githubusercontent.com/assets/11702800/14206118/5fe33984-f82e-11e5-9142-3eea09d9c57e.PNG)

**After**
![after](https://cloud.githubusercontent.com/assets/11702800/14206119/5fe5f750-f82e-11e5-94a0-70fe7be53416.PNG)

I find it quite confusing as to why I must change the syntax of my HTML file to Markdown Extended to make this wonderful package work.

_Thanks in advance!_

**Comment by jonschlinkert** [comment]
HTML isn't one of the default extensions for this package. To do what you want, do this:

<kbd>view</kbd> > <kbd>syntax</kbd> > <kbd>Open all with extension as</kbd> > <kbd>Markdown extended</kbd>
