### ISSUE TITLE
Monokai Light: gray text + white background

### ISSUE THREAD

**Issue by PixelT** [jonschlinkert/sublime-monokai-extended#66]
Hard to read / write gray text on white background :)
Please change / fix it.

![monokai](http://img.prntscr.com/img?url=http://i.imgur.com/bDpoysz.png)

Imo the comments should be in this (gray) color.

**Comment by jonschlinkert** [comment]
Here is what it looks like for me:
<img width="612" alt="screen shot 2016-05-12 at 11 04 30 am" src="https://cloud.githubusercontent.com/assets/383994/15219355/69e80590-1831-11e6-80ee-dfa85595f5d8.png">

**Comment by PixelT** [comment]
Please open some JSON file (for example Settings or Key Bindings)

**Comment by simonhaenisch** [comment]
Having the same problem with json files, though I don't use the light scheme very often, so not really an issue for me.

If you want to fix it, I think it's set in `Monokai-Extended-Light.JSON-tmTheme` in line [439](https://github.com/jonschlinkert/sublime-monokai-extended/blob/fffbf1940b3d8b60018ce15018e28904649e5be6/Monokai%20Extended%20Light.JSON-tmTheme#L439) and it should probably have the value of `string variable` (line [196](https://github.com/jonschlinkert/sublime-monokai-extended/blob/fffbf1940b3d8b60018ce15018e28904649e5be6/Monokai%20Extended%20Light.JSON-tmTheme#L196)).

The corresponding line in the `.tmTheme` file is [713](https://github.com/jonschlinkert/sublime-monokai-extended/blob/fffbf1940b3d8b60018ce15018e28904649e5be6/Monokai%20Extended%20Light.tmTheme#L713). I haven't done any color-scheme work, so I'm not familiar with how, i.e. where to change it.
