### ISSUE TITLE
Function Name Color Issue : Has same white color as normal texr

### ISSUE THREAD

**Issue by AyushRaviRai** [jonschlinkert/sublime-monokai-extended#68]
Hi,

First thanks for making this awsome theme.

I am using monokai exteneded theme.
The color of the function being called is same as the normal text color (white) , not able to diferentiate between normal text and function call.

Attaching image for reference
![functionnamecolorerror](https://cloud.githubusercontent.com/assets/11500362/15798557/8e17e810-2a59-11e6-922c-af37b7c2a144.JPG)

Please help.

**Comment by jonschlinkert** [comment]
closing since https://github.com/jonschlinkert/sublime-monokai-extended/issues/62 is related.
