### ISSUE TITLE
First bullet is wrong colour in Markdown

### ISSUE THREAD

**Issue by johnkhughes** [jonschlinkert/sublime-monokai-extended#70]
In Markdown, the first bullet is highlighted in grey which means it doesn't match all the other bullets in the list:

![markdown-bullet-issue](https://cloud.githubusercontent.com/assets/1375434/16034687/fee7a284-320a-11e6-8246-b2d1ded5d7b8.png)

I'm using build 3114 and I'm seeing the same behaviour on Mac and Linux.

**Comment by jonschlinkert** [comment]
https://github.com/jonschlinkert/sublime-monokai-extended/issues/34
