### ISSUE TITLE
Did colors change recently?

### ISSUE THREAD

**Issue by OmeGak** [jonschlinkert/sublime-monokai-extended#71]
I just realized some of the colors have changed recently in `Monokai Extended`, at least in Python. I don't know if it's a bug or intended, but it looks off to me. Please notice color changes in `def`, `int` or `basestring`.

### Monokai Extended (wrong)
![screenshot from 2016-06-14 15 43 16](https://cloud.githubusercontent.com/assets/716307/16045272/fe5b4072-3247-11e6-833b-ae1062bcd5a3.png)

### Monokai Extended Bright (correct)
![screenshot from 2016-06-14 15 43 25](https://cloud.githubusercontent.com/assets/716307/16045301/17e859b2-3248-11e6-91c1-b506c10aa309.png)

**Comment by jonschlinkert** [comment]
https://github.com/jonschlinkert/sublime-monokai-extended/issues/62
