### ISSUE TITLE
Scss `&-selector` highlighting, bug or not?

### ISSUE THREAD

**Issue by zmni** [jonschlinkert/sublime-monokai-extended#73]
![monokai-extended](https://cloud.githubusercontent.com/assets/841523/16992692/8f41d7a6-4eca-11e6-809c-d075d82a9737.png)

If highlighting is not a bug, can you make another alternative without highlight (background color), its to strong (distracting), I almost can't see the text. Also see `&-image` different from others.

**Comment by jonschlinkert** [comment]
Did you have sass syntax enabled? It looks like `css` is the current syntax

**Comment by zmni** [comment]
No, it's Scss. I have [SCSS](https://packagecontrol.io/packages/SCSS) and [CSS3](https://packagecontrol.io/packages/CSS3) package installed and internal CSS package disabled, so it already autodetect every Scss files. Here is my [full list installed packages and my user preferences](https://gist.github.com/zmni/c5560ad904bf274da9f63a34c94c36b8).

**Comment by zmni** [comment]
Found the issue. It's not compatible with [SCSS](https://packagecontrol.io/packages/SCSS) package. Removed the package and install [Sass](https://packagecontrol.io/packages/Sass), and it looks normal now. Thanks for the help, closing this now.
