### ISSUE TITLE
assign long text with newlines

### ISSUE THREAD

**Issue by bertolottipf** [jonschlinkert/sublime-monokai-extended#74]
$mail_corpo = <<<HTML
				<html>
				<head>
					<title>H.W.</title>
				</head>
				<body>
					Hello World
				</body>
				</html>
				HTML; 

breaks the colors of sublime.

**Comment by jonschlinkert** [comment]
please wrap your code in triple backticks.  Also, can you please clarify what this issue is about?

**Comment by bertolottipf** [comment]
sorry... It's with all themes... 

![schermata del 2016-11-03 16-52-30](https://cloud.githubusercontent.com/assets/3830967/19973609/fb88feb2-a1e5-11e6-9d86-873bba0890df.png)

**Comment by jonschlinkert** [comment]
closing based on age, and I'm still not sure what this issue was describing. (also the theme in the image doesn't even look like this theme)
