### ISSUE TITLE
Less Not Working

### ISSUE THREAD

**Issue by mediter** [jonschlinkert/sublime-monokai-extended#75]
Environment: ST3 (build 3126) with Syntax Highlighting for LESS, Markdown Extended, Monokai Extended installed on macOS Sierra 10.12.1 (16B2555)

Highlight for LESS not working at all.

![screen shot 2016-12-03 at 9 03 21 am](https://cloud.githubusercontent.com/assets/57368/20855495/987e3fc0-b938-11e6-82c1-8ce644953342.png)

works with CSS though
![screen shot 2016-12-03 at 9 21 35 am](https://cloud.githubusercontent.com/assets/57368/20855592/f6c81690-b939-11e6-994d-45cfb3429591.png)

**Comment by jonschlinkert** [comment]
Did you install the `less` syntax highlighting package for sublime text? also, make sure to restart ST

**Comment by mediter** [comment]
Yes, I have installed LESS syntax highlighting package for sublime text. Restarted, same issue. The syntax highlighting is working for files with .less extension.

**Comment by jonschlinkert** [comment]
I can't reproduce this issue. I'm going to go ahead and close since no one else has reported this issue and it's been a few months. But please feel free to re-open or comment if the issue persists.
