### ISSUE TITLE
Error message when loading theme

### ISSUE THREAD

**Issue by livresque** [jonschlinkert/sublime-monokai-extended#77]
This theme does not seem to be available via the Package Manager, so I created a file called Monokai Extended JSON.tmTHEME which I placed in AppData\Roaming\Sublime Text 3\Packages\User and then copied the GitHub source code into the file. I now get the following error message every time I open SublimeText:

`Error loading colour scheme Packages/User/Monokai Extended JSON.tmTHEME: Error parsing plist xml: expected < in file Packages/User/Monokai Extended JSON.tmTHEME on line: 1`

**Comment by jonschlinkert** [comment]
I'm not sure what caused this, but I'll need more information to debug. I'm going to go ahead and close since no one else has reported this since Dec. but please feel free to comment or re-open if this is still an issue
