### ISSUE TITLE
markdown URLs no longer highlighted

### ISSUE THREAD

**Issue by kaimantsch** [jonschlinkert/sublime-monokai-extended#80]
It seems like in Markdown URLs are no longer highlighted?

![screen shot 2017-01-18 at 13 49 03](https://cloud.githubusercontent.com/assets/3956933/22084428/f647f04a-dd84-11e6-8f59-4396c88ed426.png)

**Comment by kaimantsch** [comment]
Hold on - seems to be a conflict between different color schemes... will investigate further.

**Comment by jonschlinkert** [comment]
I'm not opposed to supporting this if someone wants to do a pr.

**Comment by jonschlinkert** [comment]
Closing, as I wasn't able to find anything on [CommonMark](https://commonmark.org/) about this syntax for links. Please feel free to re-open if I missed something.
