### ISSUE TITLE
search highlighting too much hard to see

### ISSUE THREAD

**Issue by shakisha** [jonschlinkert/sublime-monokai-extended#82]
How to change or personalize it?
Because in this moment it's too much hard to see.

<img width="202" alt="captura de pantalla 2017-01-30 a las 20 38 11" src="https://cloud.githubusercontent.com/assets/7482626/22438412/2e6670cc-e72c-11e6-83ed-e035b8dd6f8b.png">

**Comment by jonschlinkert** [comment]
is there a way to make this a configuration option? (it's been a while since I hacked around in ST)

**Comment by jonschlinkert** [comment]
closing due to lack of response and age
