### ISSUE TITLE
would it be difficult to add support for kramdown IALs?

### ISSUE THREAD

**Issue by clorichel** [jonschlinkert/sublime-monokai-extended#84]
[Jekyll](https://jekyllrb.com/) user here, experiencing weird highlighting with [kramdown Inline Attribute Lists](https://kramdown.gettalong.org/syntax.html#block-ials), particularly `{:target="_blank"}`.

The `_` before the `blank` word gets parsed as an _italic start_ character.

Given this text as an example:

```
It was great to showcase how to go from a legacy PHP codebase to an efficient architecture application, using [Composer](https://getcomposer.org/){:target="_blank"} and autoloading to leverage existing libraries such as [PHP Markdown](https://packagist.org/packages/michelf/php-markdown){:target="_blank"} by [Michel Fortin](https://michelf.ca/){:target="_blank"}, who himself happens to be from... Lévis in Québec, Canadian too!
```

Here is the result with latest sublime-monokai-extended version to date:

<img width="1017" alt="highlighting" src="https://cloud.githubusercontent.com/assets/12629433/23308514/ca63eba4-fa81-11e6-9f8d-cdb44d98f117.png">

On this specific example, you can see how inconvenient it is. On larger chunks (ie when there is no `_` to get parsed as an _italic end_ character), Markdown document becomes mostly unreadable...

For reference, see https://github.com/atom/language-gfm/issues/44 for similar issue on Atom.

**Comment by jonschlinkert** [comment]
> Highlighting should work as expected with kramdown IALs

Why? Is that a promised use case of this library that's mentioned somewhere?

**Comment by clorichel** [comment]
Ouch! That was no offense Jon 😄 

I'm used to describe the expected behavior as the issue title, instead of a "_italic doesn't work_" or "_highlighting bug_". I personally find it easier to manage issues coming with an appropriate title.

Rest ensure I don't feel like an open source MIT licensed project comes with _any_ promise at _any_ stage, and I'd dig in if I were more familiar with building Sublime packages and themes than "_SHIFT+CMD+P install_" 🤓 . Just thought that might be trivial for an insider, but honestly don't have a clue!

Whatever will happen to this issue, thank you and your contributors for your work over the years on this really useful package!

**Comment by jonschlinkert** [comment]
> Ouch! That was no offense Jon

Absolutely no offense taken on my part. 

> I personally find it easier to manage issues coming with an appropriate title.

Right, we share the same goal then. I was just trying to clarify if the project implied that it should be supported - since your issue title stated as much - so that we could get it fixed. If not, no worries we'll just change the title to reflect feature request or something like "hoped it would work with kramdown" instead of "should work as expected".

Sounds like the latter? If so I can change the title or you can, thanks for creating the issue. I'll take a look and see how difficult it would be to add support for kramdown.

**Comment by clorichel** [comment]
> If so I can change the title or you can, thanks for creating the issue. I'll take a look and see how difficult it would be to add support for kramdown.

Sounds fair, just did. Thank you 😁

**Comment by jonschlinkert** [comment]
closing since I think this is something that should be supported by a different plugin (which can probably work alongside this plugin)
