### ISSUE TITLE
Markdown with `***` doesn't work properly

### ISSUE THREAD

**Issue by Qwerp-Derp** [jonschlinkert/sublime-monokai-extended#85]
When I type something like this:

    ***Hello**, World!*

I expect it to be bold and italicised in `Hello`, and only italicised in `World`. However, what I get is this:

![bug](https://cloud.githubusercontent.com/assets/14177193/24318680/5d7a6e08-115d-11e7-96da-147510120ed2.PNG)

Code:

```markdown
***Hello**, World!*

This bleeds through for some reason
```
(For some reason, it doesn't work on Github either.)

As well as the issue above, the formatting also bleeds through as well, making text that's meant to be out of the bold/italics formatting formatted as bold, for some reason.

**Comment by jonschlinkert** [comment]
I think this would be a bug in ST. However, it might be better to use underscores for one of them, so you're not confusing the parser.

**Comment by Qwerp-Derp** [comment]
@jonschlinkert Ah yeah, that works. Thanks! Should I post the issue to Sublime, then?

**Comment by jonschlinkert** [comment]
> Should I post the issue to Sublime, then?

Yes, that would be great, thank you. Please also link to this issue, in case it is indeed a bug with this library (I'm pretty sure it's not, but I'm also prepared to be pretty wrong lol)

**Comment by jonschlinkert** [comment]
closing since this is not an issue with this library
